version: 2
updates:
  - package-ecosystem: npm
    directory: /assay
    schedule:
      interval: weekly
    groups:
      dev-deps:
        dependency-type: development
  - package-ecosystem: nuget
    directory: /assay.net
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
