#!/usr/bin/env node
// Runs both implementations, records every executed JS calibration line, audits the
// catalog-to-test references across JS and .NET, and derives the JSON + Markdown history.
import { execFileSync, execSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { dirname, extname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(here, '../..');
const repoRoot = resolve(pkgRoot, '..');
const resultsFile = resolve(pkgRoot, 'bench/results/latest.jsonl');
const historyFile = resolve(repoRoot, 'docs/measurements.json');
const tableFile = resolve(repoRoot, 'docs/measurements.md');
const checkOnly = process.argv.includes('--check');

function run(file, args, cwd, env = process.env) {
  execFileSync(file, args, {
    cwd,
    stdio: 'inherit',
    env,
  });
}

function sourceFiles(root, extensions) {
  const found = [];
  for (const entry of readdirSync(root)) {
    const path = resolve(root, entry);
    if (statSync(path).isDirectory()) found.push(...sourceFiles(path, extensions));
    else if (extensions.has(extname(path))) found.push(path);
  }
  return found;
}

function inputFingerprint() {
  const roots = [
    [resolve(repoRoot, 'protocol'), new Set(['.json'])],
    [resolve(pkgRoot, 'src'), new Set(['.ts', '.tsx'])],
    [resolve(pkgRoot, 'bench'), new Set(['.ts', '.tsx', '.json'])],
    [resolve(pkgRoot, 'test'), new Set(['.ts', '.tsx', '.mjs'])],
    [resolve(pkgRoot, 'tools/measure'), new Set(['.mjs'])],
    [resolve(repoRoot, 'assay.net/src'), new Set(['.cs', '.csproj'])],
    [resolve(repoRoot, 'assay.net/tests'), new Set(['.cs', '.csproj'])],
  ];
  const files = roots.flatMap(([root, extensions]) => sourceFiles(root, extensions));
  for (const path of [
    resolve(pkgRoot, 'package.json'),
    resolve(pkgRoot, 'package-lock.json'),
    resolve(pkgRoot, 'tsconfig.json'),
    resolve(pkgRoot, 'vitest.config.ts'),
    resolve(pkgRoot, 'vitest.live.config.ts'),
    resolve(pkgRoot, 'vitest.setup.ts'),
    resolve(repoRoot, 'assay.net/Assay.Net.slnx'),
  ]) {
    if (existsSync(path)) files.push(path);
  }

  const hash = createHash('sha256');
  for (const path of files.sort()) {
    hash.update(relative(repoRoot, path).replaceAll('\\', '/'));
    hash.update('\0');
    // Git may materialize the same text with CRLF on Windows and LF on Linux.
    // Scientific identity follows the normalized source, not checkout policy.
    hash.update(readFileSync(path, 'utf8').replaceAll('\r\n', '\n').replaceAll('\r', '\n'));
    hash.update('\0');
  }
  return `sha256:${hash.digest('hex')}`;
}

function measurementMarkdown(history) {
  const rows = history.map((entry) =>
    `| ${entry.date} | ${entry.commit} | ${entry.inputFingerprint?.slice(0, 19) ?? 'n/a'} | ${entry.archetypes} | ${entry.criteria} | ${entry.criteriaReferencedByTests ?? 'n/a'} | ${entry.calibrationGroups ?? 'n/a'} | ${entry.pairs} | ${entry.detected} | ${entry.falseAlarms} | ${entry.heldOutPairs ?? 'n/a'} | ${entry.heldOutDetected ?? 'n/a'} | ${entry.heldOutFalseAlarms ?? 'n/a'} |`,
  );
  return `# Measurements — the convergence table

Each row is generated by \`node tools/measure/measure.mjs\` from \`assay/\`. The
command runs the complete JS and .NET gates, records every executed JS good/bad
calibration group, and verifies that every catalog criterion is referenced by executable
test code. "Referenced" is deliberately not called calibrated: only the executed pair
columns support detection and false-alarm claims. The input fingerprint content-addresses
the catalogs, verifier implementations, fixtures, tests, measurement code, and lockfiles;
it is the reproducibility authority. The commit is the revision label at generation time,
not a self-referential claim that a report contains its own eventual Git hash. The JSON
source beside this file keeps the per-group evidence. CI reruns the same measurement in
check mode and rejects evidence, input-fingerprint, or rendered-table drift.

| date | source commit | input fingerprint | archetypes | criteria | test-referenced | calibration groups | pairs | detected | false alarms | held-out pairs | held-out detected | held-out false alarms |
|---|---|---|---|---|---|---|---|---|---|---|---|---|
${rows.join('\n')}
`;
}

rmSync(resultsFile, { force: true });

console.log('measure: running every JS calibration (ASSAY_RECORD=1)…');
run(
  process.execPath,
  [resolve(pkgRoot, 'node_modules/vitest/vitest.mjs'), 'run'],
  pkgRoot,
  { ...process.env, ASSAY_RECORD: '1' },
);

console.log('measure: running the .NET conformance and calibration suite…');
run('dotnet', ['test', '--nologo', '-warnaserror'], resolve(repoRoot, 'assay.net'));

if (!existsSync(resultsFile)) {
  throw new Error('No JS calibration records were produced. The measurement is inconclusive.');
}

const records = readFileSync(resultsFile, 'utf8')
  .trim()
  .split('\n')
  .filter(Boolean)
  .map((line) => JSON.parse(line))
  .sort((a, b) => a.label.localeCompare(b.label));
const total = records.reduce((sum, row) => sum + row.total, 0);
const detected = records.reduce((sum, row) => sum + row.detection, 0);
const falseAlarms = records.reduce((sum, row) => sum + row.falseAlarms, 0);
if (detected !== total || falseAlarms !== 0) {
  throw new Error(`Calibration failed: detected=${detected}/${total}, falseAlarms=${falseAlarms}.`);
}

const catalog = JSON.parse(readFileSync(resolve(repoRoot, 'protocol/catalog.json'), 'utf8'));
const design = JSON.parse(readFileSync(resolve(repoRoot, 'protocol/design-catalog.json'), 'utf8'));
const catalogArchetypes = [...catalog.archetypes, ...design.archetypes];
const criterionIds = catalogArchetypes.flatMap((archetype) => archetype.criteria.map((criterion) => criterion.id));
const testFiles = [
  ...sourceFiles(resolve(pkgRoot, 'bench'), new Set(['.ts', '.tsx'])),
  ...sourceFiles(resolve(pkgRoot, 'test'), new Set(['.ts', '.tsx', '.mjs'])),
  ...sourceFiles(resolve(repoRoot, 'assay.net/tests'), new Set(['.cs'])),
];
const testSources = testFiles.map((path) => ({ path, text: readFileSync(path, 'utf8') }));
const omissionPatterns = [
  /\b(?:describe|it|test)(?:\s*\.\s*\w+(?:\s*\([^;]*?\))?)*\s*\.\s*(?:skip|skipIf|todo|runIf|only)\b/s,
  /\b(?:x|f)(?:describe|it|test)\s*\(/,
  /\[(?:Fact|Theory)\s*\([^)]*\b(?:Skip|SkipWhen|SkipUnless|Explicit)\s*=/s,
];
const omittedTests = testSources
  .filter(({ text }) => omissionPatterns.some((pattern) => pattern.test(text)))
  .map(({ path }) => relative(repoRoot, path).replaceAll('\\', '/'));
if (omittedTests.length > 0) {
  throw new Error(`Scientific tests may not be skipped, conditional, explicit, or todo: ${omittedTests.join(', ')}`);
}
const missingReferences = criterionIds.filter(
  (id) => !testSources.some(({ text }) => text.includes(`'${id}'`) || text.includes(`"${id}"`) || text.includes(`\`${id}\``)),
);
if (missingReferences.length > 0) {
  throw new Error(`Catalog criteria absent from executable tests: ${missingReferences.join(', ')}`);
}

const heldOutCorpusFile = resolve(pkgRoot, 'bench/held-out/corpus.json');
const heldOutCorpus = JSON.parse(readFileSync(heldOutCorpusFile, 'utf8'));
const heldOutTests = sourceFiles(resolve(pkgRoot, 'bench/held-out'), new Set(['.ts', '.tsx']))
  .filter((path) => /\.test\.[jt]sx?$/.test(path))
  .map((path) => relative(repoRoot, path).replaceAll('\\', '/'))
  .sort();
const declaredHeldOutTests = heldOutCorpus.map((entry) => entry.test).sort();
if (new Set(heldOutCorpus.map((entry) => entry.id)).size !== heldOutCorpus.length
    || new Set(heldOutCorpus.map((entry) => entry.calibrationLabel)).size !== heldOutCorpus.length) {
  throw new Error('Held-out case ids and calibration labels must be unique.');
}
if (JSON.stringify(heldOutTests) !== JSON.stringify(declaredHeldOutTests)) {
  throw new Error('Every held-out test must appear exactly once in bench/held-out/corpus.json.');
}
for (const heldOut of heldOutCorpus) {
  if (!/^[0-9a-f]{40}$/.test(heldOut.source.commit)
      || !/^[0-9a-f]{40}$/.test(heldOut.source.parent)
      || !Array.isArray(heldOut.source.paths)
      || heldOut.source.paths.length === 0) {
    throw new Error(`Held-out case ${heldOut.id} must freeze full source revisions and changed paths.`);
  }
  const testPath = resolve(repoRoot, heldOut.test);
  if (!existsSync(testPath)) throw new Error(`Held-out case ${heldOut.id} points to missing test ${heldOut.test}.`);
  const source = readFileSync(testPath, 'utf8');
  if (!source.includes(heldOut.criterion) || !source.includes(heldOut.source.commit)) {
    throw new Error(`Held-out case ${heldOut.id} test is not bound to its frozen criterion and source commit.`);
  }
  if (!records.some((record) => record.label === heldOut.calibrationLabel)) {
    throw new Error(`Held-out case ${heldOut.id} produced no executed calibration record.`);
  }
}
const heldOutLabels = new Set(heldOutCorpus.map((entry) => entry.calibrationLabel));
const heldOutRecords = records.filter((record) => heldOutLabels.has(record.label));
if (heldOutRecords.length !== heldOutCorpus.length || heldOutRecords.some((record) => record.total < 1)) {
  throw new Error('Every held-out case must emit one non-empty calibration record.');
}

const sha = execSync('git rev-parse --short HEAD', { cwd: repoRoot, encoding: 'utf8' }).trim();
const fingerprint = inputFingerprint();
const measurement = {
  date: new Date().toISOString().slice(0, 10),
  commit: sha,
  inputFingerprint: fingerprint,
  archetypes: catalogArchetypes.length,
  criteria: criterionIds.length,
  criteriaReferencedByTests: criterionIds.length - missingReferences.length,
  calibrationGroups: records.length,
  pairs: total,
  detected,
  falseAlarms,
  heldOutCases: heldOutCorpus.length,
  heldOutPairs: heldOutRecords.reduce((sum, row) => sum + row.total, 0),
  heldOutDetected: heldOutRecords.reduce((sum, row) => sum + row.detection, 0),
  heldOutFalseAlarms: heldOutRecords.reduce((sum, row) => sum + row.falseAlarms, 0),
  calibrations: records.map(({ ts: _ts, ...record }) => record),
};

const history = existsSync(historyFile) ? JSON.parse(readFileSync(historyFile, 'utf8')) : [];
const nextHistory = [
  ...history.filter((entry) => entry.commit !== sha && entry.inputFingerprint !== fingerprint),
  measurement,
];
if (checkOnly) {
  const baseline = history.at(-1);
  if (!baseline) {
    throw new Error('No versioned measurement baseline exists. Run `npm run measure` first.');
  }

  if (baseline.inputFingerprint !== fingerprint) {
    throw new Error(
      'Scientific inputs differ from the versioned measurement fingerprint. Run `npm run measure`, review the evidence, and commit it.',
    );
  }

  const scientificEvidence = ({ date: _date, commit: _commit, ...evidence }) => evidence;
  const expected = scientificEvidence(baseline);
  const actual = scientificEvidence(measurement);
  if (JSON.stringify(actual) !== JSON.stringify(expected)) {
    throw new Error(
      'Executed measurement differs from docs/measurements.json. Run `npm run measure`, review the evidence, and commit it.',
    );
  }
  const expectedTable = measurementMarkdown(history);
  const committedTable = readFileSync(tableFile, 'utf8').replaceAll('\r\n', '\n');
  if (committedTable !== expectedTable) {
    throw new Error('docs/measurements.md is not the exact table derived from docs/measurements.json.');
  }
  console.log('measure: executed evidence matches the versioned baseline');
} else {
  mkdirSync(dirname(historyFile), { recursive: true });
  writeFileSync(historyFile, JSON.stringify(nextHistory, null, 2) + '\n');
  writeFileSync(tableFile, measurementMarkdown(nextHistory));
}

console.log(
  `measure: ${records.length} groups, ${detected}/${total} pairs detected, ${falseAlarms} false alarms, ${heldOutRecords.reduce((sum, row) => sum + row.detection, 0)}/${heldOutRecords.reduce((sum, row) => sum + row.total, 0)} held-out pairs detected, ${criterionIds.length}/${criterionIds.length} criteria test-referenced, inputs ${fingerprint}`,
);
